srusers/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # GET request to /users - calls the index method to display all the users. 
    # This will need a template.
    url(r'^users/$', views.index, name='list'),
    
    # GET request to /users/new - calls the new method to display a form allowing users to create a new user. 
    # This will need a template.
    url(r'^users/new$', views.new, name='newUser'),

    # POST to /users/create - calls the create method to insert a new user record into our database. 
    # This POST should be sent from the form on the page /users/new. 
    # Have this redirect to /users/<id> once created.
    url(r'^users/create$', views.create, name='createUser'),

    #GET /users/<id> - calls the show method to display the info for a particular user with given id. 
    #This will need a template.
    url(r'^users/(?P<id>\d+)$', views.show, name='show_user'),
    
    # GET request /users/<id>/edit - calls the edit method to display a form allowing users to edit an existing user with the given id. 
    # This will need a template.
    url(r'^users/(?P<id>\d+)/edit$', views.edit, name='editUser'),
    
    # POST /users/update - calls the update method to process the submitted form sent from /users/<id>/edit. 
    # Have this redirect to /users/<id> once updated.
    url(r'^users/update$', views.update, name='updateUser'),
    
    # GET /users/<id>/destroy - calls the destroy method to remove a particular user with the given id. 
    # Have this redirect back to /users once deleted.
    url(r'^users/(?P<id>\d+)/destroy$', views.destroy, name='userDelete'),
]

srusers/srusers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.users.urls', namespace='users') ),
    url(r'^admin/', admin.site.urls),
]

srusers/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import re

#set email regex for validation
EMAILREGEX = re.compile(r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$")

#create manager class to hold validator function
class UserManager(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['fname']) <= 2: 
            errors['first_name'] = 'first_name must be at least two characters'
        if post_data['lname'] == "":
            errors['last_name'] = 'last_name cannot be blank'
        if not EMAILREGEX.match(post_data['email']):
            errors['email'] = 'email is not properly formated.'
        return errors

class User(models.Model):
#auto-increment id is automatic
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, default = None)
    email = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()
    def __str__(self):
        return self.first_name


#**place line below in table upon which validations will be run**
#objects = userManager()
#**looping method below here.
#or to loop through post_data
#class userManager(models.Manager):
#	def validate(self, post_data):
#		for key in post_data:
#			if post_data[key] == '':  
#				 print key + 'cannot be empty

srusers/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect
from .models import *
from django.contrib import messages
from django.core.urlresolvers import reverse

#views detailed below

# GET request to /users - calls the index method to display all the users. 
# This will need a template.
def index(request):
    context = {'users': User.objects.all()}   #context must be a dict rather than QuerySet.
    return render(request, 'users/index.html', context)

#GET /users/<id> - calls the show method to display the info for a particular user with given id. 
#This will need a template.
def show(request, id):
    single = {'user': User.objects.get(id=id)}   #context must be a dict rather than QuerySet.
    return render(request, 'users/show.html', single)

# GET request /users/<id>/edit - calls the edit method to display a form allowing users to edit an existing user with the given id. 
# This will need a template.
def edit(request, id):
    single = {'user': User.objects.get(id=id)} #context must be a dict rather than QuerySet.
    return render(request, 'users/edit_user.html', single)

# POST /users/update - calls the update method to process the submitted form sent from /users/<id>/edit. 
# Have this redirect to /users/<id> once updated.
def update(request):
    #check for errors in submitted data
    request.session['id'] = request.POST['id']
    errors = User.objects.validate(request.POST)
    if not errors == {}:
        for tag, error in errors.items():
            messages.error(request, error, extra_tags=tag)
        return redirect(reverse("users:editUser", kwargs={'id': request.session['id']} ))

    #call and edit user data
    tweakUser = User.objects.get(id=request.session['id'])
    tweakUser.first_name = request.POST['fname']
    tweakUser.last_name = request.POST['lname']
    tweakUser.email = request.POST['email']
    tweakUser.save()
    
    return redirect(reverse("users:show_user", kwargs={'id': tweakUser.id} ))

# GET request to /users/new - calls the new method to display a form allowing users to create a new user. 
# This will need a template.
def new(request):
    return render(request, 'users/new_user.html')

# POST to /users/create - calls the create method to insert a new user record into our database. This POST should be sent from the form on the page /users/new. 
# Have this redirect to /users/<id> once created.
def create(request):
    errors = User.objects.validate(request.POST)
    if not errors == {}:
        for tag, error in errors.items():
            messages.error(request, error, extra_tags=tag)
        return redirect(reverse("users:newUser"))
    
    first_name = request.POST['fname']
    last_name = request.POST['lname']
    email = request.POST['email']
    
    newUser = User.objects.create(first_name=first_name, last_name=last_name, email=email )
    
    #return redirect( '/users/' + str(newUser.id) )
    return redirect(reverse ("users:show_user", kwargs={'id': newUser.id}))

# GET /users/<id>/destroy - calls the destroy method to remove a particular user with the given id. 
# Have this redirect back to /users once deleted.
def destroy(request, id):

    marked = User.objects.get(id=id)
    marked.delete()
    #response ='Hello, I am the index seed.' + id
    return redirect(reverse('users:list'))

srusers/apps/users/templates/users/edit_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <!-- <link rel="stylesheet" href="C:\Users\user\Documents\CodingDojo\Django\Holder12\srusers\apps\users\static\users\css\styles.css"> -->
    <title>Users Index</title>
</head>

<body>

    <div id="wrapper">
        <h1>Edit User{{user.id}}</h1>
        <br><br>
        {% if messages %}
            {% for message in messages %}
                <p class='lite'>{{ message }}</p>
            {% endfor %}
        {% endif %}
        <form action="{% url 'users:updateUser' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" value ="{{user.id}}">
            First name:<br>
            <input type="text" name="fname" value="{{user.first_name}}"><br>
            Last name:<br>
            <input type="text" name="lname" value="{{user.last_name}}"><br>
            Email:<br>
            <input type="text" name="email" value="{{user.email}}"><br>
            <input type="submit" value="Submit" class="bttn">
        </form>
        <a href="{% url 'users:list' %}">User List</a>
    </div>
    
    
</body>
</html>

srusers/apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <!-- <link rel="stylesheet" href="C:\Users\user\Documents\CodingDojo\Django\Holder12\srusers\apps\users\static\users\css\styles.css"> -->
    <title>Users Index</title>
</head>
<body>
    <div id="wrapper">
        <table id="userTable">
            <tr>
                <th>id</th>
                <th>Full_Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Actions</th>
            </tr>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td><a href="{% url 'users:show_user' id=user.id %}">{{ user.first_name }} {{ user.last_name }}</a></td>
                <td>{{ user.email }}</td>
                <td>{{ user.created_at }}</td>
                <td>
                    <a href="{% url 'users:show_user' id=user.id %}">Show</a>
                    <a href="{% url 'users:editUser' id=user.id %}">Edit</a>
                    <a href="{% url 'users:userDelete' id=user.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        <div id="add">
            <a href="{% url 'users:newUser' %}">Add a new user</a>
        </div>
    </div>
</body>
</html>

srusers/apps/users/templates/users/new_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <!-- <link rel="stylesheet" href="C:\Users\user\Documents\CodingDojo\Django\Holder12\srusers\apps\users\static\users\css\styles.css"> -->
    <title>Users Index</title>
</head>

<body>

    <div id="wrapper">
        <h1>Add a new user</h1>
        <br><br>
        {% if messages %}
            {% for message in messages %}
                <p class='lite'>{{ message }}</p>
            {% endfor %}
        {% endif %}
        <form action="{% url 'users:createUser' %}" method="POST">
            {% csrf_token %}
            First name:<br>
            <input type="text" name="fname"><br>
            Last name:<br>
            <input type="text" name="lname"><br>
            Email:<br>
            <input type="text" name="email"><br>
            <input type="submit" value="Submit" class="bttn">
        </form>
        <a href="{% url 'users:list' %}">User List</a>
    </div>
    
    
</body>
</html>

srusers/apps/users/templates/users/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <!-- <link rel="stylesheet" href="C:\Users\user\Documents\CodingDojo\Django\Holder12\srusers\apps\users\static\users\css\styles.css"> -->
    <title>Users Index</title>
</head>

<body>

    <div id="wrapper">
        <h1>User {{ user.id }}</h1>
        <br><br>
        <h3><span class='lite'>Full Name: </span>{{ user.first_name }} {{ user.last_name }}</h3>
        <h3><span class='lite'>Email: </span>{{ user.email }}</h3>
        <h3><span class='lite'>Created At: </span>{{ user.created_at }}</h3>
        <br>
        <a href="{% url 'users:editUser' id=user.id %}">Edit</a>
        |
        <a href="{% url 'users:userDelete' id=user.id %}">Delete</a>
        |
        <a href="{% url 'users:list' %}">List</a>
    </div>

</body>
</html>